### ISSUE TITLE
Nested Yarn Workspace in a Repo results in extraneous changelog entries

### ISSUE THREAD

**Issue by stephenliang** [monoweave/monoweave#165]
**Describe the bug**

I have a monorepo that does not use Node.js or Yarn on the root, but rather a sub-directory called `frontend` (this uses Turborepo).

When using monoweave, the CHANGELOG that is generated includes changes that are outside of the `frontend` directory. This is because when `git diff-tree` is executed, the `--relative` flag is not included, causing the parent directory changes to show up even though monoweave is located within `frontend`.

I made a change to `gitDiffTree` to include `--relative` and that seems to fix the issue (when running `yarn monoweave` in the `frontend` directory).

- [ ] I am interested in contributing a fix.

**To reproduce**

Minimal reproduction available here: https://github.com/stephenliang/monoweave-bug

1. Create a repo with folders `backend` and `frontend`
2. In `frontend`, add monoweave
3. Add a git tag
4. Make some change log entries for `backend`
5. Make some change log entries for `frontend`
6. Run `yarn monoweave` in frontend

**Expected behavior**

Only change log entries are created within `frontend`. No `backend` changelogs are created. 

```
{
  "frontend": {
    "version": "2.0.0",
    "previousVersion": "2.0.0-alpha.4",
    "changelog": "## [2.0.0](//compare/frontend@2.0.0-alpha.4...frontend@2.0.0) \"frontend\" (12/11/2024) <a name=\"2.0.0\"></a>\n\n### Changes\n\n* feat(monoweave): add monoweave ([b1d8b915](//commits/b1d8b915))",
    "tag": "frontend@2.0.0",
    "strategy": "minor",
    "group": "frontend"
  },
  "a": {
    "version": "3.1.0",
    "previousVersion": "3.0.1",
    "changelog": "## [3.1.0](//compare/a@3.0.1...a@3.1.0) \"a\" (12/11/2024) <a name=\"3.1.0\"></a>\n\n### Changes\n\n* feat(a): update readme ([29c8ce16](//commits/29c8ce16))",
    "tag": "a@3.1.0",
    "strategy": "minor",
    "group": "a"
  }
}
```

**Actual behavior**

Change log entries are created within `frontend` including `backend` changelogs.

The following Changelog was generated for the reproduction repo (notice how it includes changes for `backend`):

```
{
  "frontend": {
    "version": "2.0.0",
    "previousVersion": "2.0.0-alpha.4",
    "changelog": "## [2.0.0](//compare/frontend@2.0.0-alpha.4...frontend@2.0.0) \"frontend\" (12/11/2024) <a name=\"2.0.0\"></a>\n\n### Changes\n\n* feat(monoweave): add monoweave ([b1d8b915](//commits/b1d8b915))\n* feat(a): update readme ([29c8ce16](//commits/29c8ce16))\n* feat(backend): update docs ([8b63f5f0](//commits/8b63f5f0))",
    "tag": "frontend@2.0.0",
    "strategy": "minor",
    "group": "frontend"
  }
```

**Monoweave Configuration**

```
export default {
  preset: 'monoweave/preset-recommended',

  // Aggregates changelog entries to a single file instead of the "recommended"
  // default of per-workspace.
  changelogFilename: 'CHANGELOG.md',
  conventionalChangelogConfig: 'conventional-changelog-conventionalcommits',
  dryRun: false,
  prerelease: true,
  prereleaseId: 'alpha',
  versionStrategy: {
    minimumStrategy: 'patch',
  }
};
```

CLI (run in the `frontend` directory)
```
yarn monoweave --dry-run --log-level 0
```

- Monoweave Version: 

**Environment (please complete the following information):**

- OS: Fedora 42
- Yarn Version: 4.2.1
  - Yarn module linker: node-modules
- Node Version: 20
- Git Version: 2.47.0
- CI Tool: N/A

**Additional context**

**Comment by noahnu** [comment]
Your "patch" makes sense to me. I have a PR to add "--relative". Just need to add some test coverage before it can get merged. We should be able to mimic your repo set in an e2e test.

**Comment by noahnu** [comment]
Fixed in https://github.com/monoweave/monoweave/releases/tag/monoweave%401.11.1
